name: Deploy Laravel

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
      - name: Set up SSH for development server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.USER}}
          username: ${{ secrets.HOT_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir abc/def
            ls -al
